### ISSUE TITLE
Implémentation d'une stack de monitoring Elastic + Kibana + Fluentd

### ISSUE THREAD

**Issue by djadeau** [dnum-mi/basegun#111]
Liste des actions à mener

- [x]  Implémentation de ElasticSearch pour le dev
- [x]  Implémentation de Kibana pour le dev
- [ ] Réorganisation du répertoire monitoring
- [ ]  Correction des droits sur le datadir elastic
- [ ]  Ajout de la persistance pour Kibana
- [ ]  Implémentation de fluentbit pour les metrics
- [ ]  Suppression de metricbeat
- [ ]  Suppression de filebeat
- [ ]  Définition de métriques  Basegun

**Comment by thomashbrnrd** [comment]
Kibana est actuellement disponible sur les environnements CPiN. Sera bientôt remplacé par une stack complète Grafana.
