### ISSUE TITLE
Configurer l'envoi d'email

### ISSUE THREAD

**Issue by thomashbrnrd** [dnum-mi/basegun#397]
Ci-dessous d'autres cas d'usages sur l'envoi de demande d'avis par mail.

# Tasks
- [ ] Envoyer un mail de confirmation à l'utilisateur qui a réalisé une demande d'identification comprennant : l'ID de sa demande, date et heure de création, token d'accès spécifique à sa demande (L'objectif de cette issue est de donner accès à une demande créée à son créateur (FSI), afin de pouvoir y consulter la réponse, ou les compléments d'informations demandés par un expert.
Quand un utilisateur envoie une demande d'identification à sa permanence, il reçoit un mail avec le numéro de sa demande et une URL d'accès direct à sa demande pour y apporter des modifications (si demandé par l'expert).)

**Comment by ClemGerard** [comment]
@ClemGerard Compléter les différents cas d'envoi de mail dans cette issue

**Comment by ClemGerard** [comment]
à re prioriser en fonction de l'authentification
