### ISSUE TITLE
Mettre en place l'authentification

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#402]
Mise en place de l'authentification via le SSO Passage 2, pour permettre la remontée d'informations dans les formulaires de demandes d'avis et l'affichage des fonctionnalités de contacts uniquement pour les FSI. (Plutôt côté frontend)

# Tasks
- [x] Créer l'endpoint de login /oidc/redirect_uri
- [x] capitaliser sur la doc transmise (CR + doc sur Resana)

**Comment by ClemGerard** [comment]
Check avec équipe NEO en top prio

**Comment by ClemGerard** [comment]
Réception des documents techniques sur la collecte des ID issues de Cheops et Proxyma, et leur gestion dans Passage 2.
Analyse à suivre

**Comment by ClemGerard** [comment]
En attente de confirmation des données collectées pour assurer nos traitements

**Comment by ClemGerard** [comment]
après étude,  test avec le proxy OIDC .
Décision à venir sur l'utilisation ou non de ce proxy

**Comment by ClemGerard** [comment]
Statuer avec Lukas sur les manipulations à faire depuis un NEO pour être authentifié grâce à un token Proxyma, sur passage 2 : 
- Définir s'il a du cliquer sur un lien supplémentaire pour s'authentifier
- Si le token proxyma est reconnu par passage 2 : expérience sans clic : on l'authentifie dès le début, sans afficher l'écran de connexion passage 2.
- Si le token proxyma n'est pas reconnu par passage 2 : afficher la mire de connexion Passage 2 : avec bouton connexion via Proxyma / via Cheops.

**Comment by ClemGerard** [comment]
Implémentation transitoire : 
- bouton contacter un expert affiché en permanence
- Si clic sur ce bouton : lance le ping check réseau MI 
- Affichage de la mire de login Passage 2
- Si pas sur le réseau du MI : bouton grisé + message comme quoi l'agent n'est pas sur le réseau du MI donc n'a pas accès à la fonctionnalité

**Comment by thomashbrnrd** [comment]
https://github.com/authts/oidc-client-ts/blob/main/docs/protocols/authorization-code-grant-with-pkce.md

**Comment by leihuayi** [comment]
Tests en qualif ont un résultat étrange
