### ISSUE TITLE
CONF05_Fuite d information technique sur Nginx

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#407]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GERARDcl/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GERARDcl/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Priorité   de mise en œuvre | Complexité de   mise en œuvre
-- | --
COURT TERME | SIMPLE

</body>

</html>

### Constat
Le serveur Nginx est configuré pour retourner au client dans son entête “Server” la version exacte de Nginx utilisé. Par ailleurs, la page d’erreur 500 indique le nom du produit logiciel utilisé.

### Risque
Un attaquant pourrait utiliser cette information afin de mieux cibler les attaques réalisées sur le serveur. En affichant cette version dans ses entêtes, le serveur est également davantage visible par les scanners automatisés en recherche d’hôtes vulnérables.

# Tasks
- [ ] Il est recommandé de définir la directive “server_tokens” à “off” et de retirer la mention de nginx dans la page d’erreur 500.

**Comment by thomashbrnrd** [comment]
Pas vraiment pertinent car le repo de Basegun étant open source, nginx et sa version sont bien visibles dans le Dockerfile du frontend.
