### ISSUE TITLE
CONF10_Lancement du service uvicorn non adapte en production

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#412]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GERARDcl/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GERARDcl/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Priorité   de mise en œuvre | Complexité de   mise en œuvre
-- | --
COURT TERME | MOYENNE

</body>

</html>

### Constat
Le service uvicorn sur le conteneur de backend est lancé avec le mode “reload”, ce qui n’est pas recommandé pour une exécution en production. Ce mode est considéré comme moins stable et plus consommateur de ressources.

### Risque
Un attaquant pourrait tirer profit de l’instabilité du mode “reload” et de sa consommation de ressources afin de générer un grand nombre de requêtes sur le backend et tenter de générer un déni de service.

# Tasks
- [ ] Il est recommandé d’exposer le service uvicorn avec le mode “worker”, tel que défini dans la documentation du projet relatif au déploiement.

**Comment by thomashbrnrd** [comment]
Cette affirmation me semble fausse, voici la command lancée en production : 
```yaml
  command: 
    - uvicorn
    - --workers=2
    - --host=0.0.0.0
    - --port=5000
    - --no-server-header
    - src.main:app
  ```
