### ISSUE TITLE
Update logs content

### ISSUE THREAD

**Issue by thomashbrnrd** [dnum-mi/basegun#423]
Remove `bg_model`

**Comment by leihuayi** [comment]
Take a look at all logs and verify what is up to date, what should be removed and what should be added.
* Remove `bg_version` ?
* Add lengths info
* Maybe add some logs to track when someone uses the "mise en securité" functionality ? (to check with @ClemGerard )

**Comment by ClemGerard** [comment]
>     * Maybe add some logs to track when someone uses the "mise en securité" functionality ? (to check with @ClemGerard )
+1 : Absolument, info métier importante
