### ISSUE TITLE
changer le texte d'introduction sur la page d'info

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#459]
Mention de la DEPSA à étudier avec SCAE : convenir d'un texte de remplacement si besoin.

_En cours_

**Comment by ClemGerard** [comment]
Confirmation par Thierry OURGAUD D'ajouter en toute lettre : 
"avec le Service Central des Armes et Explosifs de la DEPSA"

En attente du GO confirmation par la com DEPSA

**Comment by ClemGerard** [comment]
GO pour intégration tel quel @thomashbrnrd @nutfdt

**Comment by nutfdt** [comment]
<img width="958" alt="accueil" src="https://github.com/dnum-mi/basegun/assets/49862152/dc320aa5-f8b9-4e0a-a679-fc1bd10aaaa1">

**Comment by nutfdt** [comment]
<img width="959" alt="a propos" src="https://github.com/dnum-mi/basegun/assets/49862152/cb3fe09f-fcb2-4a81-bf45-6fca7cbe28a9">

**Comment by ClemGerard** [comment]
to deploy ! Quick win
