### ISSUE TITLE
Préparer le Dataset d'évaluation du module d'OCR

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#468]
- [x] Préparation de la liste des photos à prendre à l'IRCGN (modèle, type de vue, poinçons)
- [x] Rédiger un protocole de création du dataset de test
- [x] Confirmer avec l'IRCGN que les armes sont disponibles chez eux
- [x] Convenir d'une date de venue pour prendre les photos
- [x] Prendre les photos
- [x] Catalogue de poinçons (vu avec Antoine Museau)
- [x] Labelliser les photos (utilisation de Label Studio, partage avec Usine IA)

**Comment by leihuayi** [comment]
Blocage dû au LabelStudio installé par l'Usine IA. @AurelienmartW attend la réponse de @victorjourne .
