### ISSUE TITLE
Evaluate image pre processing

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#472]
- [x] research on preprocessing techniques
- [x] Comparison of techniques
- [x] Pre selection of best methods
- [x] Definition of the pre processing steps (corresponding to the user path)
- [x] experimentation on small dataset
- [x] Implementation of preprocessing

**Comment by AurelienmartW** [comment]
Ameliorer automatiquement toutes les images semblent compliqué pour notre use case
Cela est possible pour des documents textes car souvent en noir sur fond blanc mais dans notre cas la couleur des armes et le type de marquage sont extrêmement variés

Une solution consiste à analyser la qualité de l'image et renoyer un message à l'utilisateur de reprendre la photo si celle-ci n'est pas de qualité suffisante

Inconvénient : analyse seuleument de qualité de l'image et pas de la gravure

Il existe plusieurs methodes d'analyse d'images ou IQA (image quality assessment

Des methodes de traitement d'images pour analyser le flou, DPI, luminosité,bruit …
Ces methodes sont rapides mais necessite de définir des seuils ce qui peut être compliqué quand les images analysées sont très variées

D'autres methodes se basent sur des modeles de deep learning et elles ne necessitent pas forcément de référence ou seuil pour analyser la qualité. Cependant elles sont plus longues à s'exécuter on sont souvent spécialisées sur des use-case particuliers (portrait, paysages…)

**Comment by ClemGerard** [comment]
Conception du parcours utilisateurs pour le pre processing : 
- Définition des cas de "bonne image" et de "mauvaise image"
- Si image bien prise => orienter l'utilisateur vers le résultat (définition de l'écran suivant à afficher)
- Si l'image est mal prise => inviter l'utilisateur à reprendre la photo (définition de l'écran suivant à afficher)

**Comment by AurelienmartW** [comment]
Présélection de 2 métriques d'evaluation de la qualité d'image sans reference.
->Brisque
->CIP-IQA

En attente du dataset de l'IRCGN pour tester et comparer la performance, la temps d'inférence et définir les seuils

**Comment by AurelienmartW** [comment]
![Image](https://github.com/dnum-mi/basegun/assets/92736328/7db0ad4b-8939-4c7d-8752-12f67a3768d7)

**Comment by AurelienmartW** [comment]
Première evaluation sur le dataset de l'IRC,
Certaines valeurs de brisque sont négatives, ce qui n'est normalement pas possible -> possible erreur d'implémentation de la librairie ?
Certain type de flou (Fond/premier plan) ne sont pas considérés comme penalisant pour brisque
Les images avec peu de contraste (Couleur arme ~couleur fond)  sont pénalisées -> impact sur la lecture ?

**Comment by AurelienmartW** [comment]
Après compariason de différentes méthodes sur un dataset de 40 images, la métrique la plus performante/légère semble être CNNIQA.
On décide d'utiliser cette solution pour la suite.
