### ISSUE TITLE
Config SMTP for basegun

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#496]
services.communs1-s1.r1.pi2.minint.fr (10.224.29.97) (main)
    services.communs2-s1.r1.pi2.minint.fr (10.224.29.98) (backup)
    10.224.29.99 (à utiliser car gère la redirection sur le backup si le main est down)

**Comment by leihuayi** [comment]
Nécessite le déploiement en qualif pour tester, on rouvrira une issue si bug
