### ISSUE TITLE
Modifier le logo BASEGUN dans la TWA

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#509]
Une dernière modification qui d'après le gendarme de l'équipe NEO peut nous permettre d'éviter de re générer une TWA avec BubbleWrap.

- [x] Mise à jour des infos dans le dossier metadata par Clément
- [x]  Vérifier si tu as bien accès au repo gendarmerie depuis ton NOEMI
- [x] Mettre à jour la qualif avec les changements armes d'alarme
- [x] Mettre à jour la preprod
- [x] Mettre à jour la prod
- [x] Build avec bubblewrap la TWA
- [x] Push la partie TWA dans le repo gendarmerie 
- [x] Demander à la gendarmerie de synchro sur NEO

[LEGACY]
- [ ] sinon appeler le gendarme NEO (passe par moi pour avoir son numéro)
- [ ] pull la branche master pour repartir de leurs dernières modifications
- [ ] modifier l'icone dans APP/SRC/MAIN/RES en reprenant l'icone dans le dossier image (celle avec un fond blanc)
- [ ] vérifier dans le twa manifest que les urls des icones sont ok

**Comment by leihuayi** [comment]
Plutôt que la solution ci-dessus, qui risque de créer des problèmes en changeant des portions de code:
1. mettre en production la nouvelle version
2. re-générer le contenu de https://github.com/dnum-mi/basegun-twa via bubblewrap
3. contacter les gendarmes pour synchro la twa chez eux

**Comment by leihuayi** [comment]
Bloqué par les problèmes de déploiement sur DSO...

**Comment by leihuayi** [comment]
Tout est fait de notre côté, attente des audits + fin période gel dû aux JO
