### ISSUE TITLE
Add SCAE images to form contact

### ISSUE THREAD

**Issue by nutfdt** [dnum-mi/basegun#533]

**Comment by nutfdt** [comment]
![Image](https://github.com/user-attachments/assets/73a995f0-baf7-4c96-84d4-33448e1ee686)

**Comment by leihuayi** [comment]
1. Le texte sur la qualité peut être davantage vulgarisé selon moi : les gens ne savent pas forcément ce qu'est l'exposition par e
  2. Mettre 4 exemples de photos pour chaque vue plutôt que seulement les 2 vues

Idée de présentation



![Image](https://github.com/user-attachments/assets/4e02bfe6-5d6c-4903-aab5-2c96716b55f3)
