### ISSUE TITLE
Add endpoint for blank gun detection

### ISSUE THREAD

**Issue by nutfdt** [dnum-mi/basegun#545]

**Comment by nutfdt** [comment]
Créer un endpoint pour appeler le modèle d'OCR lorsqu'on en a besoin

**Comment by leihuayi** [comment]
L'endpoint prend en entrée une photo de manière optionnelle.
- Si pas de photo, va utiliser l'image envoyée par l'utilisateur à la route /upload qui a été gardée en cache (TODO)
- Si photo fournie, va utiliser celle-ci

**Comment by leihuayi** [comment]
L'endpoint doit retourner au front les infos suivantes:
- qualité d'image suffisante ou non
- marquage détecté ou non, si détecté est-ce que c'est une arme d'alarme ou non (regrouper ensemble les cas PAK ou modèle de référence)

Les différents cas possibles obtenus par le module d'OCR sont visibles ici
https://github.com/dnum-mi/basegun-ml/blob/fe7eb7c6992e9e584ea765a534c74768de57accf/MLpackages/tests/test_OCR.py

**Comment by AurelienmartW** [comment]
**Attention seuls les modèles de références sont suffisant pour indiquer une arme d'alarme**
Pour l'instant on peut laisser le marquage PAK de côté avec la dernière législation
